/**
 * Exports the current project's virtual file system as a downloadable .zip that
 * runs and looks EXACTLY like the live preview.
 *
 * Parity with the preview is the whole point: the preview renders agent code via
 * Vite + the Tailwind Play CDN (so Tailwind utility classes work with zero config).
 * A naive zip without Tailwind would render unstyled. So the generated index.html
 * includes the same Tailwind CDN script — the downloaded app is styled out of the
 * box with just `npm install && npm run dev` (or even opening it through Vite).
 */
import { strToU8, zipSync } from 'fflate';

import type { ProjectFile } from '@/types/project';

const CODE_EXT = /\.(tsx|ts|jsx|js)$/;
const ENTRY_CANDIDATES = ['src/main.tsx', 'src/main.jsx', 'src/index.tsx', 'src/index.jsx'];

function safeName(projectName: string): string {
  return (
    projectName
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '') || 'ctx-space-app'
  );
}

const PACKAGE_JSON = (name: string) =>
  JSON.stringify(
    {
      name,
      private: true,
      version: '0.0.0',
      type: 'module',
      scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
      dependencies: { react: '^18.3.1', 'react-dom': '^18.3.1' },
      devDependencies: { '@vitejs/plugin-react': '^4.3.4', vite: '^5.4.10' },
    },
    null,
    2,
  );

const VITE_CONFIG = `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({ plugins: [react()] });
`;

/** index.html includes the Tailwind Play CDN so utility classes work with no build setup. */
const INDEX_HTML = (title: string, entry: string) => `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
    <!-- Tailwind Play CDN: makes utility classes (bg-indigo-600, flex, …) work
         with zero config — same as the Context Space preview. -->
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/${entry}"></script>
  </body>
</html>
`;

const MAIN_ENTRY = (appImport: string) => `import React from 'react';
import { createRoot } from 'react-dom/client';
import './index.css';
import App from '${appImport}';

createRoot(document.getElementById('root')).render(
  React.createElement(React.StrictMode, null, React.createElement(App)),
);
`;

const README = (title: string) => `# ${title}

Generated by Context Space.

## Run locally
\`\`\`bash
npm install
npm run dev
\`\`\`

Styling uses the Tailwind Play CDN (loaded in index.html), so utility classes
work without extra setup.
`;

const DEFAULT_CSS =
  "body{margin:0;font-family:system-ui,-apple-system,'Segoe UI',Roboto,sans-serif}\n";

/** Build the zip bytes — entry-aware, Tailwind-enabled, preview-faithful. */
export function buildProjectZip(
  projectName: string,
  files: Record<string, ProjectFile>,
): Uint8Array {
  const tree: Record<string, Uint8Array> = {};
  const present = new Set<string>();

  // 1. Agent files (these win over any scaffold default).
  for (const [path, file] of Object.entries(files)) {
    tree[path] = strToU8(file.contents);
    present.add(path);
  }

  // 2. Determine the real entry. If the agent only wrote App.tsx, synthesize a
  //    main entry that mounts it (matching the preview's bootstrap behavior).
  let entry = ENTRY_CANDIDATES.find((c) => present.has(c));
  if (!entry) {
    const appPath = ['src/App.tsx', 'src/App.jsx', 'App.tsx'].find((c) => present.has(c));
    const appImport = appPath
      ? './' + appPath.replace(/^src\//, '').replace(CODE_EXT, '')
      : './App';
    entry = 'src/main.jsx';
    tree[entry] = strToU8(MAIN_ENTRY(appImport));
  }

  // 3. Scaffold files only if missing.
  const name = safeName(projectName);
  if (!present.has('package.json')) tree['package.json'] = strToU8(PACKAGE_JSON(name));
  if (!present.has('vite.config.js') && !present.has('vite.config.ts')) {
    tree['vite.config.js'] = strToU8(VITE_CONFIG);
  }
  if (!present.has('index.html')) {
    tree['index.html'] = strToU8(INDEX_HTML(projectName, entry));
  } else {
    // Agent wrote its own index.html — make sure the Tailwind CDN is in it so
    // utility classes render (parity with the preview), without duplicating it.
    let html = files['index.html'].contents;
    if (!html.includes('cdn.tailwindcss.com')) {
      const tag = '<script src="https://cdn.tailwindcss.com"></script>';
      html = html.includes('</head>')
        ? html.replace('</head>', `  ${tag}\n  </head>`)
        : `${tag}\n${html}`;
      tree['index.html'] = strToU8(html);
    }
  }
  if (!present.has('src/index.css')) tree['src/index.css'] = strToU8(DEFAULT_CSS);
  if (!present.has('README.md')) tree['README.md'] = strToU8(README(projectName));

  return zipSync(tree, { level: 6 });
}

/** Build the zip and trigger a browser download. */
export function downloadProjectZip(
  projectName: string,
  files: Record<string, ProjectFile>,
): void {
  const bytes = buildProjectZip(projectName, files);
  const buf = new Uint8Array(bytes); // fresh, correctly-typed buffer for Blob
  const blob = new Blob([buf], { type: 'application/zip' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${safeName(projectName)}.zip`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
