"""Claude-backed Context Space agent (branch: ctx-space-claude).

Drop-in replacement for ``app.agent.CtxSpaceAgent`` that uses the Claude Agent
SDK as the reasoning/streaming engine instead of the OpenAI chat-completions API,
while preserving the EXACT same AG-UI event contract so the frontend (CopilotKit /
WebContainer preview) is unchanged.

Design — "Option A": Claude is the brain, the browser is the hands.
  * The frontend tools (proposePlan / writeFile / deleteFile) are NOT executed on
    the server. They run in the browser (writing into the WebContainer), exactly
    like the OpenAI path.
  * We register those tools with the SDK so Claude knows their schemas, then a
    PreToolUse HOOK intercepts every call: we emit the AG-UI TOOL_CALL_* events to
    the browser and return permissionDecision="deny" so the SDK never runs them.
    (Verified: can_use_tool does NOT block in-process SDK tools, but a PreToolUse
    hook does — and the model accepts the deny and finishes the turn cleanly.)
  * All built-in file/shell tools (Write/Edit/Bash/...) are disallowed so Claude
    can never touch the server filesystem.
  * The DataSpace MCP server is attached over HTTP and resolved by the SDK itself;
    its tool calls are allowed (they read real data the model reasons over).

Auth: the SDK authenticates with the Claude SUBSCRIPTION via CLAUDE_CODE_OAUTH_TOKEN
(generated by ``claude setup-token``). We pass it through ``options.env`` so it is
explicit. ANTHROPIC_API_KEY must NOT be set — it would override the token.

Streaming shapes (verified against claude-agent-sdk 0.2.101):
  * query(prompt=<async-iterable>, options) yields AssistantMessage / StreamEvent /
    ResultMessage. can_use_tool / hooks require the streaming-input form, so the
    prompt is always an async iterable of user-message dicts.
  * Text deltas: StreamEvent.event{type=="content_block_delta", delta{type=="text_delta", text}}
  * Tool calls: a ToolUseBlock (name, input) inside an AssistantMessage.
  * Final usage/cost: ResultMessage.total_cost_usd / .usage.
"""

from __future__ import annotations

import asyncio
import json
import uuid
from collections.abc import AsyncIterator
from typing import Any

from ag_ui.core import (
    EventType,
    RunAgentInput,
    RunErrorEvent,
    RunFinishedEvent,
    RunStartedEvent,
    TextMessageContentEvent,
    TextMessageEndEvent,
    TextMessageStartEvent,
    ToolCallArgsEvent,
    ToolCallEndEvent,
    ToolCallStartEvent,
)
from ag_ui.encoder import EventEncoder

import claude_agent_sdk as sdk

from app.config import Settings
from app.prompts import SYSTEM_PROMPT

# Built-in SDK tools we never want Claude to use — generated apps must reach the
# browser as TOOL_CALL_* events, and the server filesystem is off-limits.
# Built-in / ambient tools we never want Claude to use. Generated apps must reach
# the browser as TOOL_CALL_* events, and the server filesystem is off-limits. We
# ALSO disable session-isolation-bypassing tools (ToolSearch/Skill) and any plugin
# tools, so the only usable tools are our declared frontend tools + DataSpace MCP.
# Combined with setting_sources=[]/skills=None/plugins=[]/strict_mcp_config=True in
# _build_options, this makes each run hermetic regardless of the host's ~/.claude.
_DISALLOWED_BUILTINS = [
    "Write",
    "Edit",
    "NotebookEdit",
    "Read",
    "Bash",
    "Glob",
    "Grep",
    "WebSearch",
    "WebFetch",
    "Task",
    "TodoWrite",
    "ToolSearch",
    "Skill",
]

# In-process MCP server name that hosts our frontend tools. The SDK namespaces
# its tools as ``mcp__<server>__<tool>``.
_TOOLS_SERVER = "ctxtools"


def _frontend_tool_full_name(bare: str) -> str:
    return f"mcp__{_TOOLS_SERVER}__{bare}"


class CtxSpaceClaudeAgent:
    """Stateless agent: each ``run`` is one AG-UI request/response cycle.

    Mirrors the public surface of ``CtxSpaceAgent``:
      * ``async def run(run_input, accept) -> AsyncIterator[str]``
      * sets ``self._last_usage`` after the run for main.py's usage tracker.
    """

    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        self._last_usage: dict[str, Any] = {
            "input_tokens": 0,
            "output_tokens": 0,
            "cost_usd": 0.0,
        }
        # Build the in-process MCP server that declares our frontend tools to the
        # model. The handlers are safe no-ops (defense in depth) — the PreToolUse
        # hook denies execution before they could ever run.
        self._tools_server = self._build_tools_server()

    # ------------------------------------------------------------------ tools --
    def _build_tools_server(self) -> Any:
        """Register proposePlan / writeFile / deleteFile so Claude sees the schemas.

        Schemas mirror the contract in prompts.py. The handlers are never reached
        (the PreToolUse hook denies first); they return a sentinel just in case.
        """

        async def _noop(_args: dict[str, Any]) -> dict[str, Any]:
            return {
                "content": [
                    {"type": "text", "text": "handled-by-client"}
                ]
            }

        propose_plan = sdk.tool(
            "proposePlan",
            "Propose a build plan for the app. The user approves or requests "
            "changes before any code is written.",
            {"appName": str, "features": list, "files": list},
        )(_noop)

        write_file = sdk.tool(
            "writeFile",
            "Create or overwrite a single project file with complete, runnable "
            "contents. One file per call.",
            {"path": str, "contents": str},
        )(_noop)

        delete_file = sdk.tool(
            "deleteFile",
            "Delete a single project file by path.",
            {"path": str},
        )(_noop)

        return sdk.create_sdk_mcp_server(
            name=_TOOLS_SERVER,
            version="1.0.0",
            tools=[propose_plan, write_file, delete_file],
        )

    # --------------------------------------------------------------- messages --
    @staticmethod
    def _content_to_sdk(content: Any) -> Any:
        """Convert AG-UI message content to the SDK/Anthropic content shape.

        Plain string -> string. A list of typed parts (text / image) -> a list of
        Anthropic content blocks so vision-capable models can SEE attached images.
        """
        if content is None:
            return ""
        if isinstance(content, str):
            return content
        if not isinstance(content, list):
            return str(content)

        blocks: list[dict[str, Any]] = []
        for part in content:
            ptype = getattr(part, "type", None) or (
                part.get("type") if isinstance(part, dict) else None
            )
            if ptype == "text":
                text = getattr(part, "text", None) or (
                    part.get("text") if isinstance(part, dict) else ""
                )
                blocks.append({"type": "text", "text": text or ""})
            elif ptype == "image":
                source = getattr(part, "source", None) or (
                    part.get("source") if isinstance(part, dict) else None
                )
                if source is None:
                    continue
                stype = getattr(source, "type", None) or (
                    source.get("type") if isinstance(source, dict) else None
                )
                value = getattr(source, "value", None) or (
                    source.get("value") if isinstance(source, dict) else None
                )
                mime = (
                    getattr(source, "mime_type", None)
                    or (source.get("mime_type") if isinstance(source, dict) else None)
                    or "image/png"
                )
                if not value:
                    continue
                if stype == "url":
                    blocks.append(
                        {"type": "image", "source": {"type": "url", "url": value}}
                    )
                else:
                    blocks.append(
                        {
                            "type": "image",
                            "source": {
                                "type": "base64",
                                "media_type": mime,
                                "data": value,
                            },
                        }
                    )
            # Other modalities ignored for now.
        # If we only have a single text block, collapse to a plain string.
        if len(blocks) == 1 and blocks[0]["type"] == "text":
            return blocks[0]["text"]
        return blocks or ""

    def _ag_messages_to_sdk(self, messages: list[Any]) -> list[dict[str, Any]]:
        """Convert AG-UI history into SDK streaming-input messages (USER turns only).

        IMPORTANT: the SDK's streaming-input mode only accepts USER messages — it
        manages assistant turns internally and returns an error result if an
        ``assistant`` turn is injected. Since ctx-space is stateless (the full
        conversation is replayed from PocketBase on every run, not via SDK
        sessions), we fold prior assistant prose into the conversation as quoted
        context attached to the next user turn. This preserves multi-turn context
        without driving the SDK with assistant turns.

        Tool-call / tool-result bookkeeping from the OpenAI path is dropped: on
        this branch frontend tools execute in the browser (their effect is already
        reflected in the current file tree the user sees) and DataSpace MCP tools
        are resolved by the SDK itself.

        Image content is only attached to the FINAL user turn (the live request);
        historical turns are flattened to text to keep the replay compact.
        """
        out: list[dict[str, Any]] = []
        pending_assistant: list[str] = []

        # Identify the index of the last user message so only it keeps rich
        # (multimodal) content; earlier turns become plain text.
        last_user_idx = -1
        for i, msg in enumerate(messages):
            if getattr(msg, "role", None) == "user":
                last_user_idx = i

        for i, msg in enumerate(messages):
            role = getattr(msg, "role", None)
            raw = getattr(msg, "content", "")

            if role == "assistant":
                text = self._flatten_text(raw)
                if text:
                    pending_assistant.append(text)
                continue

            if role in ("user", "system", "developer"):
                is_last_user = i == last_user_idx and role == "user"
                content = (
                    self._content_to_sdk(raw)
                    if is_last_user
                    else self._flatten_text(raw)
                )
                if not content:
                    # Still flush any pending assistant context onto the next turn.
                    continue

                # Prepend any assistant prose seen since the previous user turn as
                # quoted context so the model retains conversational continuity.
                if pending_assistant:
                    ctx = "\n\n".join(pending_assistant)
                    prefix = (
                        f"[Earlier in this conversation, you (the assistant) said:]\n"
                        f"{ctx}\n\n[The user's message:]\n"
                    )
                    pending_assistant = []
                    if isinstance(content, str):
                        content = prefix + content
                    elif isinstance(content, list):
                        content = [{"type": "text", "text": prefix}, *content]

                out.append(
                    {"type": "user", "message": {"role": "user", "content": content}}
                )

        # If the conversation ended on assistant turns with no trailing user turn
        # (unusual), surface them as a final user nudge so the run still has input.
        if pending_assistant and not out:
            out.append(
                {
                    "type": "user",
                    "message": {
                        "role": "user",
                        "content": "\n\n".join(pending_assistant),
                    },
                }
            )
        return out

    @staticmethod
    def _flatten_text(content: Any) -> str:
        """Reduce AG-UI message content to plain text (drops images)."""
        if content is None:
            return ""
        if isinstance(content, str):
            return content
        if not isinstance(content, list):
            return str(content)
        parts: list[str] = []
        for part in content:
            ptype = getattr(part, "type", None) or (
                part.get("type") if isinstance(part, dict) else None
            )
            if ptype == "text":
                text = getattr(part, "text", None) or (
                    part.get("text") if isinstance(part, dict) else ""
                )
                if text:
                    parts.append(text)
        return "\n".join(parts)

    # ------------------------------------------------------------------- mcp --
    def _mcp_servers(self) -> dict[str, Any]:
        """The in-process frontend-tools server plus DataSpace MCP over HTTP."""
        servers: dict[str, Any] = {_TOOLS_SERVER: self._tools_server}
        url = (self._settings.mcp_server_url or "").strip()
        if url:
            servers[self._settings.mcp_server_label] = {"type": "http", "url": url}
        return servers

    def _allowed_tools(self) -> list[str]:
        """Frontend tools + every tool from the DataSpace MCP server."""
        allowed = [
            _frontend_tool_full_name("proposePlan"),
            _frontend_tool_full_name("writeFile"),
            _frontend_tool_full_name("deleteFile"),
        ]
        # Allow all DataSpace MCP tools by wildcard prefix.
        if (self._settings.mcp_server_url or "").strip():
            allowed.append(f"mcp__{self._settings.mcp_server_label}__*")
        return allowed

    # ------------------------------------------------------------------- run --
    async def run(
        self, run_input: RunAgentInput, accept: str | None
    ) -> AsyncIterator[str]:
        """Yield SSE-encoded AG-UI events for one agent run."""
        encoder = EventEncoder(accept=accept)

        yield encoder.encode(
            RunStartedEvent(
                type=EventType.RUN_STARTED,
                thread_id=run_input.thread_id,
                run_id=run_input.run_id,
            )
        )

        # Queue bridges the PreToolUse hook (which fires inside the SDK's task) to
        # this generator: the hook puts AG-UI tool-call events on the queue and we
        # drain them in order with the streamed text.
        emit_queue: asyncio.Queue[str | None] = asyncio.Queue()
        usage_acc = {"input_tokens": 0, "output_tokens": 0, "cost_usd": 0.0}

        async def pre_tool_hook(
            input_data: dict[str, Any], tool_use_id: str | None, _context: Any
        ) -> dict[str, Any]:
            """Intercept a frontend tool call: emit AG-UI events, deny execution."""
            tool_name: str = input_data.get("tool_name", "")
            tool_input: dict[str, Any] = input_data.get("tool_input", {}) or {}
            bare = tool_name.split("__")[-1]  # mcp__ctxtools__writeFile -> writeFile

            call_id = tool_use_id or str(uuid.uuid4())
            # Normalise arg key: the model uses our schema (contents/path/...).
            args_json = json.dumps(tool_input)

            await emit_queue.put(
                encoder.encode(
                    ToolCallStartEvent(
                        type=EventType.TOOL_CALL_START,
                        tool_call_id=call_id,
                        tool_call_name=bare,
                    )
                )
            )
            await emit_queue.put(
                encoder.encode(
                    ToolCallArgsEvent(
                        type=EventType.TOOL_CALL_ARGS,
                        tool_call_id=call_id,
                        delta=args_json,
                    )
                )
            )
            await emit_queue.put(
                encoder.encode(
                    ToolCallEndEvent(
                        type=EventType.TOOL_CALL_END, tool_call_id=call_id
                    )
                )
            )

            return {
                "hookSpecificOutput": {
                    "hookEventName": "PreToolUse",
                    "permissionDecision": "deny",
                    "permissionDecisionReason": (
                        "Executed client-side in the WebContainer preview."
                    ),
                }
            }

        options = self._build_options(run_input, pre_tool_hook)
        prompt_msgs = self._ag_messages_to_sdk(run_input.messages)

        async def prompt_stream() -> AsyncIterator[dict[str, Any]]:
            for m in prompt_msgs:
                yield m

        # The SDK query runs as a task; it feeds the emit_queue (tool events) and
        # we also iterate its messages for streamed text. To keep ordering simple
        # and correct, we consume the async iterator directly and drain any queued
        # tool events at each step.
        text_id: str | None = None
        try:
            agen = sdk.query(prompt=prompt_stream(), options=options)
            async for message in agen:
                # Drain any tool-call events emitted by the hook so far.
                while not emit_queue.empty():
                    item = emit_queue.get_nowait()
                    if item is not None:
                        yield item

                tname = type(message).__name__
                if tname == "StreamEvent":
                    ev = getattr(message, "event", {}) or {}
                    if ev.get("type") == "content_block_delta":
                        delta = ev.get("delta", {}) or {}
                        if delta.get("type") == "text_delta":
                            chunk = delta.get("text", "")
                            if chunk:
                                if text_id is None:
                                    text_id = str(uuid.uuid4())
                                    yield encoder.encode(
                                        TextMessageStartEvent(
                                            type=EventType.TEXT_MESSAGE_START,
                                            message_id=text_id,
                                            role="assistant",
                                        )
                                    )
                                yield encoder.encode(
                                    TextMessageContentEvent(
                                        type=EventType.TEXT_MESSAGE_CONTENT,
                                        message_id=text_id,
                                        delta=chunk,
                                    )
                                )
                elif tname == "ResultMessage":
                    self._accumulate_usage(message, usage_acc)

            # Drain any remaining queued tool events.
            while not emit_queue.empty():
                item = emit_queue.get_nowait()
                if item is not None:
                    yield item

            if text_id is not None:
                yield encoder.encode(
                    TextMessageEndEvent(
                        type=EventType.TEXT_MESSAGE_END, message_id=text_id
                    )
                )

            self._last_usage = usage_acc
            yield encoder.encode(
                RunFinishedEvent(
                    type=EventType.RUN_FINISHED,
                    thread_id=run_input.thread_id,
                    run_id=run_input.run_id,
                )
            )
        except Exception as exc:  # noqa: BLE001 — surface any failure to the client.
            # Close an open text message so the client isn't left hanging.
            if text_id is not None:
                yield encoder.encode(
                    TextMessageEndEvent(
                        type=EventType.TEXT_MESSAGE_END, message_id=text_id
                    )
                )
            yield encoder.encode(
                RunErrorEvent(type=EventType.RUN_ERROR, message=str(exc))
            )

    # --------------------------------------------------------------- helpers --
    def _build_options(
        self, run_input: RunAgentInput, pre_tool_hook: Any
    ) -> sdk.ClaudeAgentOptions:
        """Assemble ClaudeAgentOptions for one run."""
        env: dict[str, str] = {}
        token = (self._settings.claude_code_oauth_token or "").strip()
        if token:
            # Explicit subscription auth. (If blank, the SDK falls back to the
            # machine's existing `claude` login — fine for local dev.)
            env["CLAUDE_CODE_OAUTH_TOKEN"] = token

        # Match a hook to each frontend tool's full name.
        matchers = [
            sdk.HookMatcher(
                matcher=_frontend_tool_full_name(name),
                hooks=[pre_tool_hook],
            )
            for name in ("proposePlan", "writeFile", "deleteFile")
        ]

        kwargs: dict[str, Any] = dict(
            model=self._settings.claude_model,
            fallback_model=self._settings.claude_fallback_model or None,
            system_prompt=SYSTEM_PROMPT,
            mcp_servers=self._mcp_servers(),
            allowed_tools=self._allowed_tools(),
            disallowed_tools=_DISALLOWED_BUILTINS,
            hooks={"PreToolUse": matchers},
            include_partial_messages=True,
            permission_mode="default",
            max_turns=24,
            env=env,
            # --- Hermetic session: ignore the host's ~/.claude config entirely so
            # generated runs are deterministic and can't reach ambient plugins,
            # skills, settings, or MCP servers. Only what we pass here exists.
            setting_sources=[],
            skills=None,
            plugins=[],
            strict_mcp_config=True,
        )
        if self._settings.claude_max_budget_usd and self._settings.claude_max_budget_usd > 0:
            kwargs["max_budget_usd"] = self._settings.claude_max_budget_usd

        return sdk.ClaudeAgentOptions(**kwargs)

    @staticmethod
    def _accumulate_usage(result: Any, acc: dict[str, Any]) -> None:
        """Pull token counts + cost from a ResultMessage into the accumulator."""
        usage = getattr(result, "usage", None) or {}
        if isinstance(usage, dict):
            acc["input_tokens"] += int(usage.get("input_tokens", 0) or 0)
            acc["output_tokens"] += int(usage.get("output_tokens", 0) or 0)
        cost = getattr(result, "total_cost_usd", None)
        if cost:
            acc["cost_usd"] = round(acc["cost_usd"] + float(cost), 6)
