"""GitHub push — creates/updates a repo under the owner's account and commits
all project files in a single tree push.

Uses the GitHub REST API with a PAT (GITHUB_TOKEN in .env).
No OAuth needed — all repos go to the single configured account.
"""

from __future__ import annotations

import base64
import re
from typing import Any

import httpx

_BASE = "https://api.github.com"


def _headers(token: str) -> dict[str, str]:
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _slugify(name: str) -> str:
    slug = name.lower().strip()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    slug = slug.strip("-")
    return slug or "ctx-space-project"


async def _ensure_repo(
    client: httpx.AsyncClient,
    token: str,
    repo_full_name: str,
    description: str,
) -> dict[str, Any]:
    """Get existing repo or create a fresh one.

    If repo exists but is empty/broken (no commits), delete and recreate it
    so we start from a clean slate.
    """
    username = repo_full_name.split("/")[0]
    repo_name = repo_full_name.split("/")[1]

    # Check if repo exists
    r = await client.get(f"{_BASE}/repos/{repo_full_name}", headers=_headers(token))

    if r.status_code == 200:
        repo = r.json()
        # Check if it has any commits — empty repos cause 409 on blob upload
        ref_r = await client.get(
            f"{_BASE}/repos/{repo_full_name}/git/refs",
            headers=_headers(token),
        )
        has_commits = ref_r.status_code == 200 and len(ref_r.json()) > 0

        if not has_commits:
            # Delete the empty/broken repo and recreate
            await client.delete(
                f"{_BASE}/repos/{repo_full_name}", headers=_headers(token)
            )
        else:
            return repo

    # Create fresh repo WITH auto_init so GitHub creates the initial commit/tree.
    # Without this, blob uploads return 409 because the repo has no git objects yet.
    payload = {
        "name": repo_name,
        "description": description,
        "private": False,
        "auto_init": True,
    }
    cr = await client.post(
        f"{_BASE}/user/repos", headers=_headers(token), json=payload
    )
    cr.raise_for_status()
    # Small delay to let GitHub finish initialising the repo internals
    import asyncio
    await asyncio.sleep(2)
    # Re-fetch so we get the correct default_branch and latest commit info
    r2 = await client.get(f"{_BASE}/repos/{username}/{repo_name}", headers=_headers(token))
    r2.raise_for_status()
    return r2.json()


async def push_project_to_github(
    token: str,
    github_username: str,
    project_name: str,
    project_id: str,
    files: dict[str, str],
    commit_message: str | None = None,
) -> dict[str, str]:
    """Push all project files to GitHub as a single commit.

    Creates the repo if it doesn't exist. Re-creates it if it's empty/broken.
    Returns {"repo_url": "...", "repo_name": "...", "html_url": "..."}.
    """
    slug = _slugify(project_name)
    repo_short_name = f"ctx-{slug}-{project_id[:6]}"
    repo_full_name = f"{github_username}/{repo_short_name}"

    async with httpx.AsyncClient(timeout=60) as client:
        # 1. Ensure repo exists and is healthy
        repo = await _ensure_repo(
            client,
            token,
            repo_full_name,
            f"Generated by Context Space — {project_name}",
        )
        default_branch = repo.get("default_branch", "main")

        # 2. Get the latest commit SHA (if repo has commits)
        base_tree_sha: str | None = None
        parent_sha: str | None = None

        ref_r = await client.get(
            f"{_BASE}/repos/{repo_full_name}/git/ref/heads/{default_branch}",
            headers=_headers(token),
        )
        if ref_r.status_code == 200:
            parent_sha = ref_r.json()["object"]["sha"]
            commit_r = await client.get(
                f"{_BASE}/repos/{repo_full_name}/git/commits/{parent_sha}",
                headers=_headers(token),
            )
            commit_r.raise_for_status()
            base_tree_sha = commit_r.json()["tree"]["sha"]

        # 3. Create blobs for every file
        tree_items: list[dict[str, str]] = []
        for path, contents in files.items():
            blob_r = await client.post(
                f"{_BASE}/repos/{repo_full_name}/git/blobs",
                headers=_headers(token),
                json={
                    "content": base64.b64encode(contents.encode()).decode(),
                    "encoding": "base64",
                },
            )
            blob_r.raise_for_status()
            tree_items.append(
                {
                    "path": path,
                    "mode": "100644",
                    "type": "blob",
                    "sha": blob_r.json()["sha"],
                }
            )

        # 4. Create a git tree
        tree_payload: dict[str, Any] = {"tree": tree_items}
        if base_tree_sha:
            tree_payload["base_tree"] = base_tree_sha

        tree_r = await client.post(
            f"{_BASE}/repos/{repo_full_name}/git/trees",
            headers=_headers(token),
            json=tree_payload,
        )
        tree_r.raise_for_status()
        tree_sha = tree_r.json()["sha"]

        # 5. Create a commit
        commit_payload: dict[str, Any] = {
            "message": commit_message or f"Update {project_name} via Context Space",
            "tree": tree_sha,
        }
        if parent_sha:
            commit_payload["parents"] = [parent_sha]

        commit_r = await client.post(
            f"{_BASE}/repos/{repo_full_name}/git/commits",
            headers=_headers(token),
            json=commit_payload,
        )
        commit_r.raise_for_status()
        new_commit_sha = commit_r.json()["sha"]

        # 6. Update or create the branch ref
        ref_url = f"{_BASE}/repos/{repo_full_name}/git/refs/heads/{default_branch}"
        update_r = await client.patch(
            ref_url,
            headers=_headers(token),
            json={"sha": new_commit_sha, "force": False},
        )
        if update_r.status_code in (404, 422):
            # Ref doesn't exist yet — create it
            create_r = await client.post(
                f"{_BASE}/repos/{repo_full_name}/git/refs",
                headers=_headers(token),
                json={"ref": f"refs/heads/{default_branch}", "sha": new_commit_sha},
            )
            create_r.raise_for_status()
        else:
            update_r.raise_for_status()

    html_url = repo.get("html_url", f"https://github.com/{repo_full_name}")
    return {
        "repo_name": repo_full_name,
        "repo_url": html_url,
        "html_url": html_url,
        "branch": default_branch,
    }
