"""GitHub push — creates/updates a repo under the owner's account and commits
all project files in a single tree push.

Uses the GitHub REST API with a PAT (GITHUB_TOKEN in .env).
No OAuth needed — all repos go to the single configured account.
"""

from __future__ import annotations

import base64
import re
from typing import Any

import httpx

_BASE = "https://api.github.com"


def _headers(token: str) -> dict[str, str]:
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _slugify(name: str) -> str:
    """Convert a project name to a valid GitHub repo slug."""
    slug = name.lower().strip()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    slug = slug.strip("-")
    return slug or "ctx-space-project"


async def _get_or_create_repo(
    client: httpx.AsyncClient,
    token: str,
    repo_name: str,
    description: str,
) -> dict[str, Any]:
    """Return the repo metadata, creating it if it doesn't exist."""
    # Check if it exists
    r = await client.get(f"{_BASE}/repos/{repo_name}", headers=_headers(token))
    if r.status_code == 200:
        return r.json()

    # Create it
    owner_login = repo_name.split("/")[0]
    name = repo_name.split("/")[1]

    # Check if owner is an org
    user_r = await client.get(f"{_BASE}/user", headers=_headers(token))
    user_r.raise_for_status()
    me = user_r.json()["login"]

    if owner_login == me:
        create_url = f"{_BASE}/user/repos"
    else:
        create_url = f"{_BASE}/orgs/{owner_login}/repos"

    payload = {
        "name": name,
        "description": description,
        "private": False,
        "auto_init": False,
    }
    cr = await client.post(create_url, headers=_headers(token), json=payload)
    cr.raise_for_status()
    return cr.json()


async def push_project_to_github(
    token: str,
    github_username: str,
    project_name: str,
    project_id: str,
    files: dict[str, str],
) -> dict[str, str]:
    """Push all project files to GitHub as a single commit.

    Creates the repo if it doesn't exist.
    Returns {"repo_url": "...", "repo_name": "...", "html_url": "..."}.
    """
    slug = _slugify(project_name)
    # Append short project id suffix to avoid collisions
    repo_short_name = f"ctx-{slug}-{project_id[:6]}"
    repo_full_name = f"{github_username}/{repo_short_name}"

    async with httpx.AsyncClient(timeout=30) as client:
        # 1. Ensure repo exists
        repo = await _get_or_create_repo(
            client,
            token,
            repo_full_name,
            f"Generated by Context Space — {project_name}",
        )
        default_branch = repo.get("default_branch", "main")

        # 2. Get the latest commit SHA (if repo has commits)
        base_tree_sha: str | None = None
        parent_sha: str | None = None

        ref_r = await client.get(
            f"{_BASE}/repos/{repo_full_name}/git/ref/heads/{default_branch}",
            headers=_headers(token),
        )
        if ref_r.status_code == 200:
            parent_sha = ref_r.json()["object"]["sha"]
            # Get tree SHA from the commit
            commit_r = await client.get(
                f"{_BASE}/repos/{repo_full_name}/git/commits/{parent_sha}",
                headers=_headers(token),
            )
            commit_r.raise_for_status()
            base_tree_sha = commit_r.json()["tree"]["sha"]

        # 3. Create blobs for every file
        tree_items: list[dict[str, str]] = []
        for path, contents in files.items():
            blob_r = await client.post(
                f"{_BASE}/repos/{repo_full_name}/git/blobs",
                headers=_headers(token),
                json={
                    "content": base64.b64encode(contents.encode()).decode(),
                    "encoding": "base64",
                },
            )
            blob_r.raise_for_status()
            tree_items.append(
                {
                    "path": path,
                    "mode": "100644",
                    "type": "blob",
                    "sha": blob_r.json()["sha"],
                }
            )

        # 4. Create a git tree
        tree_payload: dict[str, Any] = {"tree": tree_items}
        if base_tree_sha:
            tree_payload["base_tree"] = base_tree_sha

        tree_r = await client.post(
            f"{_BASE}/repos/{repo_full_name}/git/trees",
            headers=_headers(token),
            json=tree_payload,
        )
        tree_r.raise_for_status()
        tree_sha = tree_r.json()["sha"]

        # 5. Create a commit
        commit_payload: dict[str, Any] = {
            "message": f"Update {project_name} via Context Space",
            "tree": tree_sha,
        }
        if parent_sha:
            commit_payload["parents"] = [parent_sha]

        commit_r = await client.post(
            f"{_BASE}/repos/{repo_full_name}/git/commits",
            headers=_headers(token),
            json=commit_payload,
        )
        commit_r.raise_for_status()
        new_commit_sha = commit_r.json()["sha"]

        # 6. Update (or create) the branch ref
        ref_url = f"{_BASE}/repos/{repo_full_name}/git/refs/heads/{default_branch}"
        update_r = await client.patch(
            ref_url,
            headers=_headers(token),
            json={"sha": new_commit_sha, "force": False},
        )
        if update_r.status_code == 422:
            # Ref doesn't exist yet — create it
            await client.post(
                f"{_BASE}/repos/{repo_full_name}/git/refs",
                headers=_headers(token),
                json={"ref": f"refs/heads/{default_branch}", "sha": new_commit_sha},
            )
        else:
            update_r.raise_for_status()

    html_url = repo.get("html_url", f"https://github.com/{repo_full_name}")
    return {
        "repo_name": repo_full_name,
        "repo_url": html_url,
        "html_url": html_url,
        "branch": default_branch,
    }
